steps:
  # Install dependencies using Node.js container
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd backend
        npm install --production
        
  # Create App Engine application if not exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if App Engine app exists, if not create it
        if ! gcloud app describe --project=$PROJECT_ID > /dev/null 2>&1; then
          echo "Creating App Engine application..."
          gcloud app create --region=us-central --project=$PROJECT_ID --quiet
        else
          echo "App Engine application already exists"
        fi
        
  # Deploy to App Engine using Cloud SDK
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        gcloud app deploy app.yaml --project=$PROJECT_ID --quiet

options:
  logging: CLOUD_LOGGING_ONLY
  